eventapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('events/', views.EventListView.as_view(), name='events'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event-detail'),
    path('event/create/', views.CreateEvent, name='create-event'),
    path('event/<int:pk>/delete', views.EventDelete, name='event-delete'),
    path('event/<int:pk>/update', views.EventUpdate, name='event-update'),
    path('event/<int:pk>/addtime/', views.AddTime, name='add-event-time'),
    path('event/<int:pk>/deletetime/', views.DeleteTime, name='delete-event-time'),
    path('event/filter', views.FilterEvent, name='filter-events'),
]

eventproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('placeapp/', include('placeapp.urls')),
    path('', RedirectView.as_view(url='placeapp/')),
    path('eventapp/', include('eventapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

placeapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cities/', views.CityListView.as_view(), name='cities'),
    path('places/', views.PlaceListView.as_view(), name='places'),
    path('city/<int:pk>', views.CityDetailView.as_view(), name='city-detail'),
    path('place/<int:pk>', views.PlaceDetailView.as_view(), name='place-detail'),
    path('city/create/', views.CreateCity, name='create-city'),
    path('place/create/', views.CreatePlace, name='create-place'),
    path('place/<int:pk>/delete', views.PlaceDelete, name='place-delete'),
    path('city/<int:pk>/delete', views.CityDelete, name='city-delete'),
    path('city/<int:pk>/update', views.CityUpdate, name='city-update'),
    path('place/<int:pk>/update', views.PlaceUpdate, name='place-update'),
    path('place/<int:pk>/map', views.PlaceMap, name='place-map'),
]

placeapp/models.py
from django.db import models
from django.contrib.gis.db import models as geomodels
from django.urls import reverse


class Place(models.Model):
    """Model representing a place."""
    title = models.CharField(max_length=100, help_text='Enter a place name')
    location = models.OneToOneField('Location', on_delete=models.SET_NULL, null=True, blank=True)
    description = models.CharField(max_length=500, help_text='Enter a place description')
    address = models.CharField(max_length=250, help_text='Enter a place address')
    phone = models.CharField(max_length=10, help_text='Enter a phone number')
    city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True, blank=True)
    PLACE_TYPE = (
        ('a', 'Park'),
        ('b', 'Restaurant'),
        ('c', 'Mall'),
        ('d', 'Amusement park'),
        ('e', 'Museum'),
        ('f', 'Beach'),
        ('g', 'Theater'),
        ('h', 'Lodge'),
        ('i', 'Others'),
    )
    type_of_place = models.CharField(
        max_length=1,
        choices=PLACE_TYPE,
        blank=False,
        default='m',
        help_text='Place Type',
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a particular place instance."""
        return reverse('place-detail', args=[str(self.id)])


class City(models.Model):
    """Model representing a city."""
    name = models.CharField(max_length=100, help_text='Enter a city name', null=False, blank=False)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular city instance."""
        return reverse('city-detail', args=[str(self.id)])


class Location(geomodels.Model):
    """Model representing a location."""
    name = models.CharField(max_length=100, help_text='Enter a place name',null=False, blank=False)
    point = geomodels.PointField(
        srid=4326,
        blank=True,
        )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

placeapp/forms.py
import datetime

from django import forms
from django.contrib.gis import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Location, Place, City


class CreateCityForm(forms.Form):
    name = forms.CharField(max_length=100, help_text="Enter the name of the city")


class CreatePlaceForm(forms.Form):
    title = forms.CharField(max_length=100, help_text='Enter a place name')
    location = forms.PointField(widget=forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}))
    description = forms.CharField(max_length=500, help_text='Enter a place description')
    address = forms.CharField(max_length=250, help_text='Enter a place address')
    phone = forms.CharField(max_length=10, help_text='Enter a phone number')
    city = forms.ModelChoiceField(queryset=City.objects.all())
    PLACE_TYPE = (
        ('a', 'Park'),
        ('b', 'Restaurant'),
        ('c', 'Mall'),
        ('d', 'Amusement park'),
        ('e', 'Museum'),
        ('f', 'Beach'),
        ('g', 'Theater'),
        ('h', 'Lodge'),
        ('i', 'Others'),
    )
    type_of_place = forms.ChoiceField(
        choices=PLACE_TYPE,
        help_text='Place Type',
    )


class UpdateCityForm(forms.Form):
    name = forms.CharField(max_length=100, help_text="Enter the name of the city")


class UpdatePlaceForm(forms.Form):
    title = forms.CharField(max_length=100, help_text='Enter a place name')
    location = forms.PointField(widget=forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}))
    description = forms.CharField(max_length=500, help_text='Enter a place description')
    address = forms.CharField(max_length=250, help_text='Enter a place address')
    phone = forms.CharField(max_length=10, help_text='Enter a phone number')
    city = forms.ModelChoiceField(queryset=City.objects.all())
    PLACE_TYPE = (
        ('a', 'Park'),
        ('b', 'Restaurant'),
        ('c', 'Mall'),
        ('d', 'Amusement park'),
        ('e', 'Museum'),
        ('f', 'Beach'),
        ('g', 'Theater'),
        ('h', 'Lodge'),
        ('i', 'Others'),
    )
    type_of_place = forms.ChoiceField(
        choices=PLACE_TYPE,
        help_text='Place Type',
    )

placeapp/views.py
from django.shortcuts import render
from .models import Location, Place, City
from eventapp.models import Event, Timing
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import CreateCityForm, CreatePlaceForm, UpdateCityForm, UpdatePlaceForm
from django.contrib.auth.decorators import login_required, permission_required
import datetime


def index(request):
    """View function for home page of site."""

    num_places = Place.objects.all().count()
    num_cities = City.objects.all().count()
    total_events = Event.objects.all().count()
    date = datetime.date.today()
    num_upcoming = Timing.objects.filter(date__gte=date).count()

    context = {
        'num_places': num_places,
        'num_cities': num_cities,
        'total_events': total_events,
        'num_upcoming': num_upcoming,
    }

    return render(request, 'index.html', context=context)


class CityListView(generic.ListView):
    model = City
    paginate_by = 10


class PlaceListView(generic.ListView):
    model = Place
    paginate_by = 10


class CityDetailView(generic.DetailView):
    model = City
    paginate_by = 10


class PlaceDetailView(generic.DetailView):
    model = Place
    paginate_by = 10


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def CreateCity(request):
    """View function for Creating city."""

    if request.method == 'POST':

        form = CreateCityForm(request.POST)

        if form.is_valid():
            city = City(name=form.cleaned_data['name'])
            city.save()

            return HttpResponseRedirect(reverse('cities') )

    else:
        form = CreateCityForm()

    context = {
        'form': form,
    }

    return render(request, 'placeapp/create_city.html', context)


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def CreatePlace(request):
    """View function for Creating Place."""

    if request.method == 'POST':

        form = CreatePlaceForm(request.POST)

        if form.is_valid():
            location = Location(name=form.cleaned_data['title'],point=form.cleaned_data['location'])
            location.save()
            place = Place(title=form.cleaned_data['title'],description=form.cleaned_data['description'],address=form.cleaned_data['address'],phone=form.cleaned_data['phone'],city=form.cleaned_data['city'],type_of_place=form.cleaned_data['type_of_place'],location=location)
            place.save()

            return HttpResponseRedirect(reverse('places'))

    else:
        form = CreatePlaceForm()

    context = {
        'form': form,
    }

    return render(request, 'placeapp/create_place.html', context)


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def PlaceDelete(request, pk):
    """View function for deleting the place."""
    place = get_object_or_404(Place, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        place.delete()
        return HttpResponseRedirect(reverse('places'))

    context = {
        'place': place,
    }

    return render(request, 'placeapp/delete_place.html', context)


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def CityDelete(request, pk):
    """View function for deleting the city."""
    city = get_object_or_404(City, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        city.delete()
        return HttpResponseRedirect(reverse('places'))

    context = {
        'city': city,
    }

    return render(request, 'placeapp/delete_city.html', context)


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def CityUpdate(request, pk):
    """View function for updating city."""
    city = get_object_or_404(City, pk=pk)

    if request.method == 'POST':

        form = UpdateCityForm(request.POST)

        if form.is_valid():
            city.name = form.cleaned_data['name']
            city.save()
            return HttpResponseRedirect(reverse('cities'))

    else:
        city_original_name = city.name
        form = UpdateCityForm(initial={'name': city_original_name})

    context = {
        'form': form,
        'city': city,
    }

    return render(request, 'placeapp/update_city.html', context)


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def PlaceUpdate(request, pk):
    """View function for updating Place."""
    place = get_object_or_404(Place, pk=pk)

    if request.method == 'POST':

        form = UpdatePlaceForm(request.POST)

        if form.is_valid():
            place.title = form.cleaned_data['title']
            place.description = form.cleaned_data['description']
            place.address = form.cleaned_data['address']
            place.phone = form.cleaned_data['phone']
            place.city = form.cleaned_data['city']
            place.type_of_place = form.cleaned_data['type_of_place']
            place.location.point = form.cleaned_data['location']
            place.location.save()
            place.save()
            return HttpResponseRedirect(reverse('places'))

    else:
        place_original_title = place.title
        place_original_description = place.description
        place_original_address = place.address
        place_original_phone = place.phone
        place_original_city = place.city
        place_original_type_of_place = place.type_of_place
        place_original_location = place.location.point
        form = UpdatePlaceForm(initial={'title': place_original_title,'description':place_original_description,'address':place_original_address,'phone':place_original_phone,'city':place_original_city,'type_of_place':place_original_type_of_place, 'location':place_original_location})

    context = {
        'form': form,
        'place': place,
    }

    return render(request, 'placeapp/update_place.html', context)

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def PlaceMap(request, pk):
    """View function for deleting the place."""
    place = get_object_or_404(Place, pk=pk)

    context = {
        'place': place,
    }

    return render(request, 'placeapp/map_place.html', context)

placeapp/templates/placeapp/city_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>City name : {{ city.name }}</h1>
  <br>
  <h4><button class="mybutton"><a href="{% url 'city-delete' city.id %}">Delete City</a></button></h4>
  <h4><button class="mybutton"><a href="{% url 'city-update' city.id %}">Update City</a></button></h4>
  <br>
    <h3>Places : </h3>
  <br>
  {% if city.place_set.all %}
  <ul>
    {% for place in city.place_set.all %}
      <li>
        <a class="mylist-ele" href="{{ place.get_absolute_url }}">{{ place.title }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no places added in this {{ city.name }} city.</p>
  {% endif %}
{% endblock %}

placeapp/templates/placeapp/city_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>City List</h1>
  <h4><button class="mybutton"><a href="{% url 'create-city' %}">Create City</a></button></h4>
  {% if city_list %}
  <table style="width:100%">
    {% for city in city_list %}
    <tr>
      <th style="text-align: center;"><a class="mylist-ele" href="{{ city.get_absolute_url }}">{{ city.name }}</a></th>
      <th><button class="mybutton"><a href="{% url 'city-delete' city.id %}">Delete</a></button></th>
      <th><button class="mybutton"><a href="{% url 'city-update' city.id %}">Update</a></button></th>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no city created in this app.</p>
  {% endif %}
{% endblock %}

placeapp/templates/placeapp/create_city.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Create City</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

placeapp/templates/placeapp/create_place.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Create Place</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

placeapp/templates/placeapp/delete_city.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete City</h1>
    <h4>City : {{ city.name }}</h4>
  <form action="" method="post">
      {% csrf_token %}
    <input type="submit" value="Are you sure">
  </form>
{% endblock %}

placeapp/templates/placeapp/delete_place.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Delete Place</h1>
    <h4>Place : {{ place.title }}</h4>
  <form action="" method="post">
      {% csrf_token %}
    <input type="submit" value="Are you sure">
  </form>
{% endblock %}

placeapp/templates/placeapp/map_place.html
{% extends "base_generic.html" %}

{% block content %}


<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
  crossorigin=""></script>

<div id="mapid" style="height: 250%;">

  <script>
    var zoom = 15
    var lat = {{ place.location.point.y }}
    var lon = {{ place.location.point.x }}
    var mymap = L.map('mapid').setView([ lat, lon, {{world_border.lon}}], zoom);

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a>',
      //maxZoom: 15,
      subdomains: ['a','b','c']
      }).addTo(mymap);

    var marker = L.marker([ lat, lon ]).addTo(mymap);

  </script>
</div>

{% endblock %}

placeapp/templates/placeapp/place_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Place: {{ place.title }}</h1>

  <h4><button class="mybutton"><a href="{% url 'place-delete' place.id %}">Delete Place</a></button></h4>
  <h4><button class="mybutton"><a href="{% url 'place-update' place.id %}">Update Place</a></button></h4>

  <p><strong>City:</strong> <a class="mylist-ele" href="{{ place.city.get_absolute_url }}">{{ place.city.name }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Address:</strong> {{ place.address }}</p>
  <p><strong>Phone:</strong> {{ place.phone }}</p>
  <p><strong>Description:</strong> {{ place.description }}</p>
  <p><strong>Type of place:</strong> {{ place.get_type_of_place_display }}</p>
  <p><strong>Location:</strong> {{ place.location.point }} </p><h6><button class="mybutton"> <a href="{% url 'place-map' place.id %}">Show in map</a></button></h6>

{% endblock %}

placeapp/templates/placeapp/place_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Place List</h1>
  <h4><button class="mybutton"><a href="{% url 'create-place' %}">Create Place</a></button></h4>
  {% if place_list %}
  <table style="width:100%">
    {% for place in place_list %}
    <tr>
      <th style="text-align: center;"><a class="mylist-ele" href="{{ place.get_absolute_url }}">{{ place.title }}</a></th>
      <th><button class="mybutton"><a href="{% url 'place-delete' place.id %}">Delete</a></button></th>
      <th><button class="mybutton"><a href="{% url 'place-update' place.id %}">Update</a></button></th>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no place created in this app.</p>
  {% endif %}
{% endblock %}

placeapp/templates/placeapp/update_city.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Update City</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

placeapp/templates/placeapp/update_place.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Update Place</h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}